### PR TITLE
Changing fallback config value to Sentinel

### PR DESCRIPTION
**Pull request by mvdstam**

### CODE REVIEW

**Comment by nWidart** [comment]
Please send a PR against develop next time.

**Comment by mvdstam** [comment]
Could you please tag this release?

**Comment by nWidart** [comment]
Sorry, will do tomorrow :+1:

**Comment by nWidart** [comment]
Done on 1.4.0, https://github.com/AsgardCms/User/releases/tag/1.4.0 , sorry for the delay.

**Comment by mvdstam** [comment]
Thanks!

**Pull request merged**
